### PR TITLE
Fix useScroll usage

### PR DESCRIPTION
**Pull request by OlegWock**

### CODE REVIEW

**Comment by OlegWock** [comment]
Bro upvote my answer on SO please...

**Comment by kori6810** [comment]
Yeah, sure! But What is SO?

**Comment by OlegWock** [comment]
Stackoverflow, you posted question there https://stackoverflow.com/questions/77349948/framer-motion-scrollyprogress-is-not-updating/77361759#77361759

**Comment by kori6810** [comment]
Yeah sure

**Pull request merged**
